export const GROUP_REPOSITORY_RUNTIME_VERSION = 2
export const GROUP_RUNTIME_ENGINE_REF = `group-runtime-v${GROUP_REPOSITORY_RUNTIME_VERSION}`
export const GROUP_RECALCULATION_WORKFLOW_PATH = '.github/workflows/fantazone-group.yml'

/**
 * Managed Fantazone group workflow installed into every Fantazone.<group> repository.
 *
 * The file is intentionally copied into the group repository because group-owned
 * jobs must execute with that repository's GITHUB_TOKEN. The implementation stays
 * shared in KeyserDSoze/Fantazone but is pinned to the engine ref associated with
 * this group runtime version; it never follows moving `main` in production.
 *
 * Bump GROUP_REPOSITORY_RUNTIME_VERSION whenever this managed template (or another
 * mandatory group-managed artifact) changes in a way existing group repositories
 * must receive, then publish the matching group-runtime-vN engine ref.
 */
export const GROUP_RECALCULATION_WORKFLOW = [
  '# Managed by Fantazone. Local edits to this file are overwritten by runtime upgrades.',
  `# group-runtime-version: ${GROUP_REPOSITORY_RUNTIME_VERSION}`,
  'name: Fantazone group maintenance',
  '',
  'on:',
  '  workflow_dispatch:',
  '    inputs:',
  '      job:',
  '        description: Group job to execute',
  '        required: true',
  '        type: choice',
  '        options:',
  '          - recalculate-day',
  '          - recalculate-all',
  '          - set-next-formations',
  '      day:',
  '        description: Optional Serie A day (required by recalculate-day)',
  '        required: false',
  '        type: string',
  '      season:',
  '        description: Optional Fantazone season id',
  '        required: false',
  '        type: string',
  '',
  'permissions:',
  '  contents: write',
  '',
  'concurrency:',
  '  group: fantazone-group-maintenance-${{ github.repository }}',
  '  cancel-in-progress: false',
  '',
  'env:',
  '  FANTAZONE_JOB: ${{ inputs.job }}',
  '  FANTAZONE_DAY: ${{ inputs.day }}',
  '  FANTAZONE_SEASON: ${{ inputs.season }}',
  '',
  'jobs:',
  '  run:',
  '    runs-on: ubuntu-latest',
  '    steps:',
  '      - name: Checkout group repository',
  '        uses: actions/checkout@v6',
  '        with:',
  '          path: group',
  '',
  '      - name: Checkout Fantazone engine and global football data',
  '        uses: actions/checkout@v6',
  '        with:',
  '          repository: KeyserDSoze/Fantazone',
  `          ref: ${GROUP_RUNTIME_ENGINE_REF}`,
  '          path: platform',
  '',
  '      - uses: actions/setup-node@v6',
  '        with:',
  '          node-version: 22',
  '',
  '      - name: Install Fantazone engine dependencies',
  '        working-directory: platform',
  '        run: npm install',
  '',
  '      - name: Run selected group job',
  '        working-directory: platform',
  '        env:',
  '          FANTAZONE_GROUP_REPO_ROOT: ${{ github.workspace }}/group',
  '          FANTAZONE_PLATFORM_REPO_ROOT: ${{ github.workspace }}/platform',
  '        run: npm run job --workspace=@fantazone/jobs -- "$FANTAZONE_JOB" "$FANTAZONE_DAY" "$FANTAZONE_SEASON"',
  '',
  '      - name: Commit canonical group data changes',
  '        working-directory: group',
  '        shell: bash',
  '        run: |',
  '          if [ -z "$(git status --porcelain -- data)" ]; then',
  '            echo "No canonical group data changes"',
  '            exit 0',
  '          fi',
  '          git config user.name "fantazone-actions[bot]"',
  '          git config user.email "fantazone-actions[bot]@users.noreply.github.com"',
  '          git add -A -- data',
  '          git commit -m "data: $FANTAZONE_JOB"',
  '          git push',
  '',
].join('\n')
